<a href="https://colab.research.google.com/github/ankitkumar0021/ankit/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Libraries in python

In [2]:
#Numpy

In [3]:
import numpy as np

In [4]:
a1 = np.array([2,4,5,6])
a1

array([2, 4, 5, 6])

In [6]:
a1 = np.array([[3,4,5],[5,6,7]])
a1

array([[3, 4, 5],
       [5, 6, 7]])

In [7]:
type(a1)

numpy.ndarray

In [9]:
z1 = np.zeros((2,2))      #zeros method in numpy 2*2 array with zero entries
z1

array([[0., 0.],
       [0., 0.]])

In [11]:
z2 = np.zeros((4,6))
z2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
#For a specific number we use full method
f1 = np.full((2,2),10)
f1 

array([[10, 10],
       [10, 10]])

In [15]:
# a range method
ar1 = np.arange(1,15)
ar1
#it does not include 15

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
ar2 = np.arange(2,20,3)   # For giving a special gap 
ar2

array([ 2,  5,  8, 11, 14, 17])

In [27]:
# For taking the random integer number
ri1 = np.random.randint(1,50,100)   # n is numbers of array's elements
ri1

array([27, 32, 46, 21, 47, 10, 44, 34,  6, 18, 35, 35, 39, 27, 37, 48, 24,
       46, 16,  4,  2, 39, 37, 38, 44, 19, 35, 45, 36, 30, 21, 11, 43, 41,
        8, 19, 20, 22, 42, 35, 17, 11,  5, 20,  3, 33, 15, 10, 23,  5,  4,
       23, 12,  3,  9,  7, 19, 26, 27,  8, 35, 40, 32, 31, 10,  5, 46,  9,
       28,  1, 21, 31, 39, 30, 41, 12, 24,  5, 29, 31, 35, 47, 30,  1, 42,
       46, 46,  1, 30, 18, 15, 42, 10, 18, 12, 41, 24, 47, 13, 19])

In [28]:
# shape of numpy array

In [29]:
s1 = np.array([[1,2,3,4],[4,3,2,1]])
s1

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [38]:
s1.shape = (4,2)
s1


array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [39]:
# Joining of two arrays

In [44]:
#vetically Stack
v1 = np.array([1,2,3,4])
v2 = np.array([1,2,3,4])
v3 = np.array([1,2,3,4])

np.vstack((v1,v2,v3))


array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [45]:
#Horizontally stack
h1 = np.array([1,2,3,4])
h2 = np.array([1,2,3,4])
h3 = np.array([1,2,3,4])

np.hstack((h1,h2,h3))

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [46]:
#coloumn_stack
cs1 = np.array([1,2,3,4])
cs2 = np.array([1,2,3,4])
cs3 = np.array([1,2,3,4])

np.column_stack((cs1,cs2,cs3))

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [49]:
#Inresection and set difference
n1 = np.array([1,2,3,4,5,6])
n2 = np.array([3,4,5,6,7,8,9])
np.intersect1d(n1,n2)

array([3, 4, 5, 6])

In [50]:
n1 = np.array([1,2,3,4,5,6])
n2 = np.array([3,4,5,6,7,8,9])
np.setdiff1d(n1,n2)

array([1, 2])

In [51]:
n1 = np.array([1,2,3,4,5,6])
n2 = np.array([3,4,5,6,7,8,9])
np.setdiff1d(n2,n1)                           #reversing n1,n2

array([7, 8, 9])